name: Build Docker Images

on: push

jobs:
  qtcreator-clang:
    name: "QtCreator"
    strategy:
      fail-fast: false
      matrix:
        distro: ['noble']
        clang: [
          {major: 16, source: 'apt'},
          {major: 17, source: 'llvm'},
          {major: 18, source: 'llvm'}
        ]
        gcc: [
          {major: 13, source: 'apt'},
          {major: 14, source: 'apt'}
        ]
        qt: [
          {version: '6.5.3', arch: 'gcc_64'},
          {version: '6.6.3', arch: 'gcc_64'},
          {version: '6.7.2', arch: 'linux_gcc_64'}
        ]
        qtcreator: [
          {version: "14.0.1", url: "https://github.com/qt-creator/qt-creator/releases/download/v14.0.1/qtcreator-linux-x64-14.0.1.7z"},
          {version: "14.0.1-patched", url: "https://github.com/hicknhack-software/Qt-Creator/releases/download/v14.0.0-patched/qtcreator-linux-x64-10100609914.7z"}
        ]

        include:
          - distro: noble
            clang: {major: 18, source: 'llvm'}
            gcc: {major: 14, source: 'apt'}
            qt_version: {version: '6.7.1', arch: 'linux_gcc_64'}
            qtcreator: {version: "14.0.1-patched", url: "https://github.com/hicknhack-software/Qt-Creator/releases/download/v14.0.0-patched/qtcreator-linux-x64-10100609914.7z"}
            clang_tags: |
              arbmind/qtcreator-clang:latest
              ghcr.io/arbmind/qtcreator-clang:latest
            clang_libstdcpp_tags: |
              arbmind/qtcreator-clang-libstdcpp:latest
              ghcr.io/arbmind/qtcreator-clang-libstdcpp:latest
            clang_libstdcpp_qt_tags: |
              arbmind/qtcreator-clang-libstdcpp-qt:latest
              ghcr.io/arbmind/qtcreator-clang-libstdcpp-qt:latest
            gcc_tags: |
              arbmind/qtcreator-gcc:latest
              ghcr.io/arbmind/qtcreator-gcc:latest
            gcc_qt_tags: |
              arbmind/qtcreator-gcc-qt:latest
              ghcr.io/arbmind/qtcreator-gcc-qt:latest

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: QtCreator ${{ matrix.qtcreator.version }} + Clang${{ matrix.clang.major }}
        uses: docker/build-push-action@v6
        with:
          target: qtcreator-clang
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/qtcreator-clang:${{ matrix.qtcreator.version }}-${{ matrix.clang.major }}
            ghcr.io/arbmind/qtcreator-clang:${{ matrix.qtcreator.version }}-${{ matrix.clang.major }}
            ${{ matrix.clang_tags }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            CLANG_MAJOR=${{ matrix.clang.major }}
            CLANG_SOURCE=${{ matrix.clang.source }}
            QT_CREATOR_VERSION=${{ matrix.qtcreator.version }}
            QTCREATOR_URL=${{ matrix.qtcreator.url }}
            QTCREATOR_VERSION=${{ matrix.qtcreator.version }}

      - name: QtCreator ${{ matrix.qtcreator.version }} + Clang${{ matrix.clang.major }} + libstdc++-${{ matrix.gcc.major }}
        uses: docker/build-push-action@v6
        with:
          target: qtcreator-clang-libstdcpp
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/qtcreator-clang-libstdcpp:${{ matrix.qtcreator.version }}-${{ matrix.clang.major }}-${{ matrix.gcc.major }}
            ghcr.io/arbmind/qtcreator-clang-libstdcpp:${{ matrix.qtcreator.version }}-${{ matrix.clang.major }}-${{ matrix.gcc.major }}
            ${{ matrix.clang_libstdcpp_tags }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            GCC_MAJOR=${{ matrix.gcc.major }}
            GCC_SOURCE=${{ matrix.gcc.source }}
            CLANG_MAJOR=${{ matrix.clang.major }}
            CLANG_SOURCE=${{ matrix.clang.source }}
            QT_VERSION=${{ matrix.qt.version }}
            QT_ARCH=${{ matrix.qt.arch }}
            QTCREATOR_URL=${{ matrix.qtcreator.url }}
            QTCREATOR_VERSION=${{ matrix.qtcreator.version }}

      - name: QtCreator ${{ matrix.qtcreator.version }} + Clang${{ matrix.clang.major }} + libstdc++-${{ matrix.gcc.major }} + Qt-${{ matrix.qt.version }}
        uses: docker/build-push-action@v6
        with:
          target: qtcreator-clang-libstdcpp-qt
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/qtcreator-clang-libstdcpp-qt:${{ matrix.qtcreator.version }}-${{ matrix.clang.major }}-${{ matrix.gcc.major }}-${{ matrix.qt.version }}
            ghcr.io/arbmind/qtcreator-clang-libstdcpp-qt:${{ matrix.qtcreator.version }}-${{ matrix.clang.major }}-${{ matrix.gcc.major }}-${{ matrix.qt.version }}
            ${{ matrix.clang_libstdcpp_qt_tags }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            GCC_MAJOR=${{ matrix.gcc.major }}
            GCC_SOURCE=${{ matrix.gcc.source }}
            CLANG_MAJOR=${{ matrix.clang.major }}
            CLANG_SOURCE=${{ matrix.clang.source }}
            QT_VERSION=${{ matrix.qt.version }}
            QT_ARCH=${{ matrix.qt.arch }}
            QTCREATOR_URL=${{ matrix.qtcreator.url }}
            QTCREATOR_VERSION=${{ matrix.qtcreator.version }}

      - name: QtCreator ${{ matrix.qtcreator.version }} + GCC${{ matrix.gcc.major }}
        uses: docker/build-push-action@v6
        with:
          target: qtcreator-gcc
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/qtcreator-gcc:${{ matrix.qtcreator.version }}-${{ matrix.gcc.major }}
            ghcr.io/arbmind/qtcreator-gcc:${{ matrix.qtcreator.version }}-${{ matrix.gcc.major }}
            ${{ matrix.gcc_tags }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            GCC_MAJOR=${{ matrix.gcc.major }}
            GCC_SOURCE=${{ matrix.gcc.source }}
            QT_VERSION=${{ matrix.qt.version }}
            QT_ARCH=${{ matrix.qt.arch }}
            QTCREATOR_URL=${{ matrix.qtcreator.url }}
            QTCREATOR_VERSION=${{ matrix.qtcreator.version }}

      - name: QtCreator ${{ matrix.qtcreator.version }} + GCC${{ matrix.gcc.major }} + Qt-${{ matrix.qt.version }}
        uses: docker/build-push-action@v6
        with:
          target: qtcreator-gcc-qt
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/qtcreator-gcc-qt:${{ matrix.qtcreator.version }}-${{ matrix.gcc.major }}-${{ matrix.qt.version }}
            ghcr.io/arbmind/qtcreator-gcc-qt:${{ matrix.qtcreator.version }}-${{ matrix.gcc.major }}-${{ matrix.qt.version }}
            ${{ matrix.gcc_qt_tags }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            GCC_MAJOR=${{ matrix.gcc.major }}
            GCC_SOURCE=${{ matrix.gcc.source }}
            QT_VERSION=${{ matrix.qt.version }}
            QT_ARCH=${{ matrix.qt.arch }}
            QTCREATOR_URL=${{ matrix.qtcreator.url }}
            QTCREATOR_VERSION=${{ matrix.qtcreator.version }}
